"use client";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/DashboardCom/Header";
import Sidebar from "@/components/DashboardCom/Sidebar";
import Cards from "@/components/DashboardCom/Cards";
import Layout from "@/components/DashboardCom/layout";
import RecentActivities from "@/components/DashboardCom/RecentActivities";
import HouseIcon from "@mui/icons-material/House";
import AccessTimeIcon from "@mui/icons-material/AccessTime";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
function Homepage() {
  return (
    <>
      <Head>
        <title>BSMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="bg-gray-100 min-h-screen flex-grow">
          <div className="ml-7">
            <Header />
          </div>
        </main>
      </Layout>
    </>
  );
}
export default Homepage;
