import Head from 'next/head';
import Image from 'next/image';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import Cards from '@/components/Cards';
import Layout from '@/components/layout';


 function Homepage() {
  return (
    <>
      <Head>
        <title>BSMS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
  <div className="flex">
    <main className='bg-gray-100 min-h-screen flex-grow ml-60'>
      <Header />
      <div className="ml-4 flex flex-col"> 
        <Cards />
      </div>
    </main>
  </div>
</Layout>


    </>
  );
}
export default Homepage;
