"use client";
import Head from "next/head";
import Image from "next/image";
import Header from "@/components/DashboardCom/Header";
import Sidebar from "@/components/DashboardCom/Sidebar";
import Cards from "@/components/DashboardCom/Cards";
import Layout from "@/components/DashboardCom/layout";
import RecentActivities from "@/components/DashboardCom/RecentActivities";
import HouseIcon from "@mui/icons-material/House";
import AccessTimeIcon from "@mui/icons-material/AccessTime";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
function Homepage() {
  return (
    <>
      <Head>
        <title>BSMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="bg-gray-100 min-h-screen flex-grow">
          <div className="ml-7">
            <Header />
          </div>
          <div className="ml-4 flex flex-wrap md:gap-2 lg:gap-0 sm:gap-2">
            {/* Display three Cards in a row with equal width */}
            <div className="flex flex-grow justify-center lg:w-1/3 md:w-full sm:w-full ">
              <Cards title="Total Properties" amount="4" icon={HouseIcon} />
            </div>
            <div className="flex flex-grow justify-center lg:w-1/3 md:w-full sm:w-full">
              <Cards
                title="Pending Properties"
                amount="2"
                icon={AccessTimeIcon}
              />
            </div>
            <div className="flex flex-grow justify-center lg:w-1/3 md:w-full sm:w-full">
              <Cards title="Published " amount="2" icon={CloudUploadIcon} />
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
}
export default Homepage;
